USE [ProfilesRNS]
GO
/****** Object:  Table [Ontology.].[DataMap]    Script Date: 02/10/2014 17:35:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [Ontology.].[DataMap](
  [DataMapID] [int] NOT NULL,
  [DataMapGroup] [int] NULL,
  [IsAutoFeed] [bit] NULL,
  [Graph] [bigint] NULL,
  [Class] [varchar](400) NULL,
  [NetworkProperty] [varchar](400) NULL,
  [Property] [varchar](1000) NULL,
  [MapTable] [varchar](max) NULL,
  [sInternalType] [varchar](1000) NULL,
  [sInternalID] [varchar](1000) NULL,
  [cClass] [varchar](400) NULL,
  [cInternalType] [varchar](1000) NULL,
  [cInternalID] [varchar](1000) NULL,
  [oClass] [varchar](400) NULL,
  [oInternalType] [varchar](1000) NULL,
  [oInternalID] [varchar](1000) NULL,
  [oValue] [varchar](1000) NULL,
  [oDataType] [varchar](1000) NULL,
  [oLanguage] [varchar](1000) NULL,
  [oStartDate] [varchar](1000) NULL,
  [oStartDatePrecision] [varchar](1000) NULL,
  [oEndDate] [varchar](1000) NULL,
  [oEndDatePrecision] [varchar](1000) NULL,
  [oObjectType] [bit] NULL,
  [Weight] [varchar](1000) NULL,
  [OrderBy] [varchar](1000) NULL,
  [ViewSecurityGroup] [varchar](1000) NULL,
  [EditSecurityGroup] [varchar](1000) NULL,
  [_ClassNode] [bigint] NULL,
  [_NetworkPropertyNode] [bigint] NULL,
  [_PropertyNode] [bigint] NULL,
 CONSTRAINT [PK__DataMap__966C304141713BA7] PRIMARY KEY CLUSTERED 
(
  [DataMapID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (154, 1, 1, 2337, N'http://vivoweb.org/ontology/core#ResearcherRole', NULL, NULL, N'[Profile.Data].[Grant.AffiliatedPeople]', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 1484, NULL, NULL)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (155, 1, 1, 2339, N'http://xmlns.com/foaf/0.1/Person', NULL, N'http://vivoweb.org/ontology/core#hasResearcherRole', N'(SELECT *  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople] where IsPrincipalInvestigator = 0) t', N'Person', N'PersonID', NULL, NULL, NULL, N'http://vivoweb.org/ontology/core#ResearcherRole', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 48, NULL, 1445)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (156, 1, 1, 2340, N'http://vivoweb.org/ontology/core#ResearcherRole', NULL, N'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', N'(SELECT *  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople] where IsPrincipalInvestigator = 0) t', N'Role', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, N'''http://vivoweb.org/ontology/core#Role''', NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 1484, NULL, 14)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (157, 1, 1, 2341, N'http://vivoweb.org/ontology/core#ResearcherRole', NULL, N'http://www.w3.org/2000/01/rdf-schema#label', N'(SELECT gi.GrantTitle as GrantTitle, ga.GrantID as GrantID  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople]  ga INNER JOIN [ProfilesRNS].[Profile.Data].[Grant.Information] gi on ga.GrantID = gi.GrantID where IsPrincipalInvestigator = 0) t', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, N'GrantTitle', NULL, NULL, NULL, NULL, NULL, NULL, 1, N'1', NULL, N'-1', N'-40', 1484, NULL, 15)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (158, 1, 1, 2342, N'http://vivoweb.org/ontology/core#ResearcherRole', NULL, N'http://vivoweb.org/ontology/core#researcherRoleOf', N'(SELECT ga.PersonID as PersonID, ga.GrantID  as GrantID  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople]  ga INNER JOIN [ProfilesRNS].[Profile.Data].[Grant.Information] gi on ga.GrantID = gi.GrantID where IsPrincipalInvestigator = 0) t', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, N'http://xmlns.com/foaf/0.1/Person', N'Person', N'PersonID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 1484, NULL, 1485)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (159, 1, 1, 2343, N'http://vivoweb.org/ontology/core#ResearcherRole', NULL, N'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', N'(SELECT *  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople] where IsPrincipalInvestigator = 0) t', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, N'''http://vivoweb.org/ontology/core#ResearcherRole''', NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 1484, NULL, 14)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (160, 1, 1, 2344, N'http://vivoweb.org/ontology/core#PrincipalInvestigatorRole', NULL, NULL, N'[Profile.Data].[Grant.AffiliatedPeople]', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 1474, NULL, NULL)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (161, 1, 1, 2345, N'http://xmlns.com/foaf/0.1/Person', NULL, N'http://vivoweb.org/ontology/core#hasPrincipalInvestigatorRole', N'(SELECT *  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople] where IsPrincipalInvestigator = 1) t', N'Person', N'PersonID', NULL, NULL, NULL, N'http://vivoweb.org/ontology/core#PrincipalInvestigatorRole', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 48, NULL, 1472)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (162, 1, 1, 2346, N'http://vivoweb.org/ontology/core#PrincipalInvestigatorRole', NULL, N'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', N'(SELECT *  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople] where IsPrincipalInvestigator = 1) t', N'Role', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, N'''http://vivoweb.org/ontology/core#Role''', NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 1474, NULL, 14)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (163, 1, 1, 2347, N'http://vivoweb.org/ontology/core#PrincipalInvestigatorRole', NULL, N'http://www.w3.org/2000/01/rdf-schema#label', N'(SELECT gi.GrantTitle as GrantTitle, ga.GrantID as GrantID  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople]  ga INNER JOIN [ProfilesRNS].[Profile.Data].[Grant.Information] gi on ga.GrantID = gi.GrantID where IsPrincipalInvestigator = 1) t', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, N'GrantTitle', NULL, NULL, NULL, NULL, NULL, NULL, 1, N'1', NULL, N'-1', N'-40', 1474, NULL, 15)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (164, 1, 1, 2348, N'http://vivoweb.org/ontology/core#PrincipalInvestigatorRole', NULL, N'http://vivoweb.org/ontology/core#researcherRoleOf', N'(SELECT ga.PersonID as PersonID, ga.GrantID  as GrantID  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople]  ga INNER JOIN [ProfilesRNS].[Profile.Data].[Grant.Information] gi on ga.GrantID = gi.GrantID where IsPrincipalInvestigator = 1) t', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, N'http://xmlns.com/foaf/0.1/Person', N'Person', N'PersonID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 1474, NULL, 1485)
INSERT [Ontology.].[DataMap] ([DataMapID], [DataMapGroup], [IsAutoFeed], [Graph], [Class], [NetworkProperty], [Property], [MapTable], [sInternalType], [sInternalID], [cClass], [cInternalType], [cInternalID], [oClass], [oInternalType], [oInternalID], [oValue], [oDataType], [oLanguage], [oStartDate], [oStartDatePrecision], [oEndDate], [oEndDatePrecision], [oObjectType], [Weight], [OrderBy], [ViewSecurityGroup], [EditSecurityGroup], [_ClassNode], [_NetworkPropertyNode], [_PropertyNode]) VALUES (165, 1, 1, 2349, N'http://vivoweb.org/ontology/core#PrincipalInvestigatorRole', NULL, N'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', N'(SELECT *  FROM [ProfilesRNS].[Profile.Data].[Grant.AffiliatedPeople] where IsPrincipalInvestigator = 1) t', N'ResearcherRole', N'GrantID', NULL, NULL, NULL, NULL, NULL, NULL, N'''http://vivoweb.org/ontology/core#ResearcherRole''', NULL, NULL, NULL, NULL, NULL, NULL, 0, N'1', NULL, N'-1', N'-40', 1474, NULL, 14)
